feed/urls.py
from django.urls import path
from .views import HomePageView
from .views import PostDetailView
from .views import AddPostView

app_name='feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(),name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

myproject1/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import messages
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text=models.CharField(max_length=140, blank=False, null=False)
    image=ImageField()
    
    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image=forms.FileField()
    text=forms.CharField(label="Description")

feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .models import Post
from .forms import PostForm

class HomePageView(TemplateView):
    template_name="home.html"
    
    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['posts']=Post.objects.all()
        return context
    
class PostDetailView(DetailView):
    template_name="detail.html"
    model=Post

class AddPostView(FormView):
    template_name="new_post.html"
    form_class=PostForm
    success_url="/"
    
    def dispatch(self, request,*args,**kwargs):
        self.request=request
        return super().dispatch(request,*args,**kwargs)
    
    def form_valid(self, form):
        new_object=Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )

        messages.add_message(self.request, messages.SUCCESS, 'Your post was successful')
        return super().form_valid(form)

feed/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {%if messages%}
        <ul class="messages">
            {%for message in messages%}
            <li>{%if message.tags%} class="{{message.tags}}"{%endif%}>{{message}}</li>
            {%endfor%}
        </ul>
    {%endif%}
        {% include 'includes/header.html' %}
   

      <div class="container">
    {% block body %}{% endblock %}
      </div>
      {%include 'includes/footer.html' %}
</body>
</html>

feed/templates/detail.html
{%extends "base.html"%}

{%block title%}Detail View{%endblock%}

{%block body%}
    <a href="{%url 'feed:index' %}">&larr; Go back</a>
    <div class="row">
        <div class="col-sm-10 offset-sm-1 py-5">
            {{object.text}}
            <img src="{{object.image.url}}"  class='img-fluid rounded' style='width:100%; height:auto;'>
        <div>
    </div>
{%endblock%}

feed/templates/home.html
{%extends "base.html"%}
{% load thumbnail %}

{% block title %} Awesome Home Page{% endblock %}

{% block body %}

    <a href="{% url 'feed:post' %}">Add a new post &rarr;</a>
    <hr/>

    <div class="row">
    {% for post in posts %}
    <div class="col-sm-4 col-md-3">
        <div class="card" style="width: 18rem;">
            {% thumbnail post.image "100x100" crop="center" as im %}
            <img src="{{im.url}}" class="card-img-top" alt="...">
            {% endthumbnail %}
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">{{post.text}}</p>
              <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">View Full Image</a>
            </div>
          </div>
        </div>
        {%empty%}
        <div class="container">
            <h2>Upload an image</h2>
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        {% csrf_token %}
        {{ form.as_p}}
        <div>
            <button type="submit" class="btn btn-success">Submit form</form>
            </div>
        </div>
    {% endfor %}
    </div>
{%endblock %}

feed/templates/includes/footer.html
<div class="container-fluid">
<footer style="padding:20px;margin-top:10px;background-color:#000000;color:#ffffff;">

<h4>All Rights reserved &copy;Developer<h4>
    <nav class="navbar navbar-expand-lg">
          <a class="navbar-brand" href="#">ABCDXYZ</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
          </div>
        </div>
      </nav>

</footer>
</div>

feed/templates/includes/header.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="text-align-center;font-size:24px;font-weight:bold;margin:10px;background-color:background-color:beige;color:brown;">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Image Sharing Application</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{% url 'feed:index' %}">Home</a>
          <a class="nav-link" href="{% url 'feed:post' %}">Images Posted</a>
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </div>
      </div>
    </div>
  </nav>

feed/templates/new_post.html
{%extends "base.html"%}

{%block title%}Upload an image{%endblock%}

{%block body%}
    <form method="POST" action="" enctype="multipart/form-data" class="col-sm-4 offset-4 py-5 my-5">
        {% csrf_token %}
        {{ form.as_p}}
        <div>
            <button type="submit" class="btn btn-success">Submit form</form>
        </div>

{%endblock%}